import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProviders } from "@/provider/auth/ui/auth";
import { AppSidebar } from "@/components/app-sidebar";
import {
  MainContent,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { useLayout } from "@/hooks/use-layout";
import Header from "@/components/ux/sidebar/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProviders>
          <div className="root">
            <SidebarProvider
              collapsibleType="icon"
              defaultLayout={await useLayout("main-layout-persistence")}
              groupId="main-layout-persistence"
            >
              <AppSidebar />
              <MainContent className="flex flex-col">
                <Header>
                  <SidebarTrigger />
                </Header>
                {children}
              </MainContent>
            </SidebarProvider>
          </div>
        </AuthProviders>
      </body>
    </html>
  );
}
